#: schema https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json
name = "sdchi-auth"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-05-15"
# account_id should be set via environment variable CLOUDFLARE_ACCOUNT_ID
# or passed as a command line argument

[dev]
port = 3001

[vars]
BASE_URL = "https://auth.labs.localhost.localdomain:3000"

[[d1_databases]]
binding = "DB"
database_name = "sdchi-auth-db"
database_id = "sdchi-auth-db"
migrations_dir = "drizzle"

# Dev Env overrides
[[env.preview.d1_databases]]
binding = "DB"
database_name = "dev-sdchi-auth-db"
database_id = "d4a8939e-8ebc-4357-8b86-35b1723cb60e"
migrations_dir = "drizzle"

[env.preview.vars]
BASE_URL = "https://auth-preview.yourdomain.com"

# Prod env overrides
[[env.production.d1_databases]]
binding = "DB"
database_name = "prod-sdchi-auth-db"
database_id = "53825883-7d7b-4cb0-89c6-7e1319282365"
migrations_dir = "drizzle"

[env.production.vars]
BASE_URL = "https://auth.yourdomain.com"
