#: schema https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json
name = "sdchi-auth"
main = ".output/server/index.mjs"
compatibility_date = "2025-05-15"
# account_id should be set via environment variable CLOUDFLARE_ACCOUNT_ID
# or passed as a command line argument

[env.preview]
name = "sdchi-auth"

[env.production]
name = "sdchi-auth"

[dev]
port = 3001

[vars]
BASE_URL = "https://auth.labs.localhost.localdomain:3000"

[[d1_databases]]
binding = "DB"
database_name = "sdchi-auth-db"
database_id = "sdchi-auth-db"
migrations_dir = "drizzle"

# Dev Env overrides
[[env.preview.d1_databases]]
binding = "DB"
database_name = "dev-sdchi-auth-db"
database_id = "fb8d7c8c-d473-4b55-8ce7-2b618ee49c55"
migrations_dir = "drizzle"

[env.preview.vars]
BASE_URL = "https://auth-dev.sdchi.jp"

# Prod env overrides
[[env.production.d1_databases]]
binding = "DB"
database_name = "prod-sdchi-auth-db"
database_id = "4f232c56-9728-46a8-b6fa-3ed6e48eba4e"
migrations_dir = "drizzle"

[env.production.vars]
BASE_URL = "https://auth.sdchi.jp"
