name = "sdchi-jp"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sdchi-signups-dev"
database_id = "a685a159-bb54-49fb-9c9f-590e984a043a"
migrations_dir = "drizzle/migrations"

[env.production]
name = "sdchi-jp"

[[env.production.d1_databases]]
binding = "DB"
database_name = "sdchi-signups"
database_id = "2ac3467d-ea4e-44e9-acd3-f6ce9b2e2b41"  # To be filled when D1 database is created
migrations_dir = "drizzle/migrations"

[env.preview]
name = "sdchi-jp-dev"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "sdchi-signups-dev"
database_id = "a685a159-bb54-49fb-9c9f-590e984a043a"
migrations_dir = "drizzle/migrations"
